language: ruby
addons:
  postgresql: "9.4"
rvm:
 - "2.3.3"
cache: bundler
bundler_args: --without development
before_script:
  - "for i in config/*.sample; do cp \"$i\" \"${i/.sample}\"; done"
  - bundle exec rake db:setup
script:
  - "bundle exec rake assets:precompile RAILS_ENV=test"
  - bundle exec rspec
