staging:
  deploy_to: "/aytomad/app/VOLUN/volunt_frontend"
  ssh_port: 22
  server: staging.volunt_frontend.madrid.es
  user: xxxxx
  full_app_name: volunt_frontend
  server_name: staging.volunt_frontend.madrid.es
  db_server: postgre.volunt_frontend.madrid.es
  stage: 'preproduction'
  server_name: 'rorapppre06A.munimadrid.es'
  server: 'rorapppre06A.munimadrid.es'
  user:   'deploy'

preproduction:
  deploy_to: "/aytomad/app/VOLUN/volunt_frontend"
  ssh_port: 22
  server1: xxx.xxx.xxx.xxx
  server2: xxx.xxx.xxx.xxx
  full_app_name: volunt_frontend
  db_server: xxx.xxx.xxx.xxx
  stage: 'preproduction'
  server_name: 'rorapppre06A.munimadrid.es'
  server: 'rorapppre06A.munimadrid.es'
  user:   'deploy'

production:
  deploy_to: "/aytomad/app/VOLUN/volunt_frontend"
  ssh_port: 22
  server: xxx.xxx.xxx.xxx
  user: xxxxx
  full_app_name: volunt_frontend
  stage: 'preproduction'
  server_name: 'rorapppre06A.munimadrid.es'
  server: 'rorapppre06A.munimadrid.es'
  user:   'deploy'
