staging:
  deploy_to: "/aytomad/app/VOLUN/volun_frontend"
  ssh_port: 22
  server: staging.volun_frontend.madrid.es
  user: xxxxx
  full_app_name: volun_frontend
  server_name: staging.volun_frontend.madrid.es
  db_server: xxx.xxx.xxx.xxx
  stage: 'staging'
  server_name: 'rorappdesa06A.munimadrid.es'
  server: 'rorappdesa06A.munimadrid.es'
  user:   'deploy'

preproduction:
  deploy_to: "/aytomad/app/VOLUN/volun_frontend"
  ssh_port: 22
  server1: xxx.xxx.xxx.xxx
  server2: xxx.xxx.xxx.xxx
  full_app_name: volun_frontend
  db_server: xxx.xxx.xxx.xxx
  stage: 'preproduction'
  server_name: 'rorapppre06A.munimadrid.es'
  server: 'rorapppre06A.munimadrid.es'
  user:   'deploy'

production:
  deploy_to: "/aytomad/app/VOLUN/volun_frontend"
  ssh_port: 22
  full_app_name: volun_frontend
  stage: 'production'
  server_name: 'rorapppro06A.munimadrid.es'
  server: 'rorapppro06A.munimadrid.es'
  user:   'deploy'
