# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3c1ea5a53eeb3a47bb4ff2d7f5d08f47194fb0682f046e11ac5a1a88c078371432c417c9487fc45eb28737dc38092dc193c56ef34cf3eae714e244e375c17bf
  url_rotulacion: https://sigmapre.madrid.es/arcgis/rest/services/SIGMA/MPROTULACION/MapServer
  #url_rotulacion: http://sigmadesa.madrid.es/arcgis/rest/services/SIGMA/MPROTULACION/MapServer
  url_map: https://sigmapre.madrid.es/arcgis/rest/services/SIGMA/MPCARTO_BASE_2013/MapServer
  #url_map: http://arcgis93desa.munimadrid.es:8399/arcgis/rest/services/Urbanismo/CARTO_BASE_LIGERA/MapServer
  #url_ndps: https://sigmapre.madrid.es/arcgis/rest/services/SIGMA/MPNDPS/MapServer
  nas_images: /
  



test:
  secret_key_base: c85bda6ecd7c9fca202c743a90e63785845733ee11b9eb48d98ede2da9d03fc4b7e130e5076ec6859fd434d30fcf5011b6b8a489b0b404493d16af4ede9dd732

preproduction:
  secret_key_base: c3c1ea5a53eeb3a47bb4ff2d7f5d08f47194fb0682f046e11ac5a1a88c078371432c417c9487fc45eb28737dc38092dc193c56ef34cf3eae714e244e375c17bf
  url_rotulacion: //sigmapre.madrid.es/arcgis/rest/services/SIGMA/MPROTULACION/MapServer
  url_map: //sigmapre.madrid.es/arcgis/rest/services/SIGMA/MPCARTO_BASE_2013/MapServer
  url_ndps: //sigmapre.madrid.es/arcgis/rest/services/SIGMA/MPNDPS/MapServer
  nas_images: /

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  url_rotulacion: //sigmapre.madrid.es/arcgis/rest/services/SIGMA/MPROTULACION/MapServer
  url_map: //sigmapre.madrid.es/arcgis/rest/services/SIGMA/MPCARTO_BASE_2013/MapServer
  url_ndps: //sigmapre.madrid.es/arcgis/rest/services/SIGMA/MPNDPS/MapServer
  nas_images: /
